// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAivgrrUwVXRkf3ihPdlAGZRCRtHWBpeGc',
    appId: '1:883781263237:web:9d8c388d7f0612a3e3aeec',
    messagingSenderId: '883781263237',
    projectId: 'shopping-ecf9d',
    authDomain: 'shopping-ecf9d.firebaseapp.com',
    storageBucket: 'shopping-ecf9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL3Fs9Ws5VYubaKWzPi9vjqOIbbl_yiZI',
    appId: '1:883781263237:android:a3a4bea14c710639e3aeec',
    messagingSenderId: '883781263237',
    projectId: 'shopping-ecf9d',
    storageBucket: 'shopping-ecf9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA49HgGDzjMRyTTZv7hfedcVQPrmWe-ick',
    appId: '1:883781263237:ios:dc7356d5cf816361e3aeec',
    messagingSenderId: '883781263237',
    projectId: 'shopping-ecf9d',
    storageBucket: 'shopping-ecf9d.appspot.com',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA49HgGDzjMRyTTZv7hfedcVQPrmWe-ick',
    appId: '1:883781263237:ios:dc7356d5cf816361e3aeec',
    messagingSenderId: '883781263237',
    projectId: 'shopping-ecf9d',
    storageBucket: 'shopping-ecf9d.appspot.com',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAivgrrUwVXRkf3ihPdlAGZRCRtHWBpeGc',
    appId: '1:883781263237:web:048d5577a995c815e3aeec',
    messagingSenderId: '883781263237',
    projectId: 'shopping-ecf9d',
    authDomain: 'shopping-ecf9d.firebaseapp.com',
    storageBucket: 'shopping-ecf9d.appspot.com',
  );
}
